pref('extensions.VimFx.hint_chars',             'fjdkslaghrueiwovncm');
pref('extensions.VimFx.prev_patterns',          'prev,previous,‹,«,◀,←,<<,<,back,newer');
pref('extensions.VimFx.next_patterns',          'next,›,»,▶,→,>>,>,more,older');
pref('extensions.VimFx.scroll_step_lines',      6);
pref('extensions.VimFx.black_list',             '*example.com*');
pref('extensions.VimFx.prevent_autofocus',      true);
pref('extensions.VimFx.autofocus_limit',        100);
pref('extensions.VimFx.ignore_keyboard_layout', false);
pref('extensions.VimFx.translations',           '{}');
